services:
  db:
    image: postgres
    restart: always
    ports:
      - '5438:5432'
    volumes:
      - ./pgdata:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
